import type { Metadata } from "next";
import "./globals.css";
import BackButton from "@/components/ts/backBotton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className="relative h-screen flex flex-col justify-center bg-black m-0 p-0">
        {children}
      </body>
    </html>
  );
}